### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by tourze** [rollerworks/password-common-list#2]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

**Comment by sstok** [comment]
Symfony 6 is supported by the composer.json file btw, what exactly is current missing or not working as expected?

**Comment by tourze** [comment]
> Symfony 6 is supported by the composer.json file btw, what exactly is current missing or not working as expected?

https://github.com/rollerworks/password-common-list/blob/28090c023f595653f5ba6e0ee2d15c38759028c9/composer.json#L28

Only support symfony framework 5.x currently.
